<?php
/**
 * @file
 * Code for the Uber Publisher Author Profile feature.
 */

include_once 'uber_publisher_author_profile.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alter all views_content_views_panes_content_type forms.
 */
function uber_publisher_author_profile_form_views_content_views_panes_content_type_edit_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['exposed']['filter-field_author_target_id']['field_author_target_id'])) {
    $form['exposed']['filter-field_author_target_id']['field_author_target_id']['#autocomplete_path'] = 'entityreference/autocomplete/single/field_author/node/uber_publisher_article/2';
    $form['exposed']['filter-field_author_target_id']['field_author_target_id']['#element_validate'][] = '_entityreference_autocomplete_validate';
  }

}
