<?php

function uber_publisher_amp_preprocess_amp__node(&$variables) {
  $block_manager = \Drupal::service('plugin.manager.block');
  $config = [];

  $plugin_block = $block_manager->createInstance('uber_publisher_amp_header', $config);
  $access_result = $plugin_block->access(\Drupal::currentUser());
  if (is_object($access_result) && $access_result->isForbidden() || is_bool($access_result) && !$access_result) {
    // You might need to add some cache tags/contexts.
    $variables['uber_publisher_amp_header'] = '';
  }
  $render = $plugin_block->build();
  $variables['uber_publisher_amp_header'] = $render;

  $plugin_block = $block_manager->createInstance('uber_publisher_amp_footer', $config);
  $access_result = $plugin_block->access(\Drupal::currentUser());
  if (is_object($access_result) && $access_result->isForbidden() || is_bool($access_result) && !$access_result) {
    // You might need to add some cache tags/contexts.
    $variables['uber_publisher_amp_header'] = '';
  }
  $render = $plugin_block->build();
  $variables['uber_publisher_amp_footer'] = $render;
}
