<?php
/**
 * @file
 * Contains uber_publisher_breaking_news.module..
 */

/**
 * Implements hook_install().
 */
// function uber_publisher_breaking_news_install() {
//     $moduleHandler = \Drupal::service('module_handler');
//     if ($moduleHandler->moduleExists('uber_publisher_demo_content')){
// 		if (\Drupal::languageManager()->getCurrentLanguage()->getId() == 'ar') {
// 			\Drupal::service('module_installer')->install(['uber_publisher_breaking_news_demo_content_arabic']);
// 		} else {
// 			\Drupal::service('module_installer')->install(['uber_publisher_breaking_news_demo_content_english']);
// 		}
//     }
// }
