<?php

/**
 * @file
 * Code for the Uber Publisher Article feature.
 */

include_once 'uber_publisher_article.features.inc';

/**
 * Implements hook_ctools_plugin_directory()
 *
 */
function uber_publisher_article_ctools_plugin_directory($module, $plugin) {
  if ($module == 'page_manager' || $module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_libraries_info().
 *
 */
function uber_publisher_article_libraries_info() {
  $libraries = array();

  $libraries['jQuery.Marquee'] = array(
    'name' => 'jQuery.Marquee',
    'vendor url' => 'https://github.com/aamirafridi/jQuery.Marquee',
    'download url' => 'https://github.com/aamirafridi/jQuery.Marquee/archive/1.3.1.tar.gz',
    'version arguments' => array(
      'file' => 'jquery.marquee.js',
      'pattern' => '/jQuery.marquee/',
      'lines' => 2,
    ),
    'version callback' => '_jquery_marquee_version',
    'files' => array(
      'js' => array(
        'jquery.marquee.min.js',
      )
    )
  );

  return $libraries;
}

function _jquery_marquee_version() {
  // This is to prevent libraries from actually checking the vesion
  return TRUE;
}

function uber_publisher_article_preprocess_views_view(&$variables) {
  $view = &$variables['view'];
  $view_name = $variables['name'];
  $display_id = $variables['display_id'];

  if ($view_name != 'uber_publisher_latest_bar')
    return;
  switch ($display_id) {
    case 'news_ticker':
      libraries_load('jQuery.Marquee');
      drupal_add_js(drupal_get_path('module', 'uber_publisher_article') . '/js/news-ticker.js');
      drupal_add_css(drupal_get_path('module', 'uber_publisher_article') . '/css/news-ticker.css');
      break;
    case 'latest_news_vertical_bar':
      drupal_add_css(drupal_get_path('module', 'uber_publisher_article') . '/css/latest-news-vertical-bar.css');
      break;
  }
}
