<?php

/**
 * @file
 * Code for the Uber Publisher newsletter feature.
 */

include_once 'uber_publisher_newsletter.features.inc';

/**
 * Implementation of hook_apps_app_info()
 */
function uber_publisher_newsletter_apps_app_info() {
  return array(
    'configure form' => 'uber_publisher_newsletter_configure_form',
  );
}

/**
 * Configuration Form for Uber Publisher Newsletter.
 * 
 */
function uber_publisher_newsletter_configure_form() {
  $form['newsletter'] = _uber_publisher_newsletter_form();
  return system_settings_form($form);
}

/**
 * Implementation of hook_form_FORM_ID_alter()
 *
 * Configuration Form for Uber Publisher newsletter.
 */
function uber_publisher_newsletter_form_uber_publisher_social_alter(&$form, &$form_state, $form_id) {
  $form['newsletter'] = _uber_publisher_newsletter_form();
}

/**
 * Implementation of hook_form_FORM_ID_alter()
 *
 * Configuration Form for Uber Publisher Newsletter.
 */
function _uber_publisher_newsletter_form() {
  $form = array(
    '#type' => 'fieldset',
    '#group' => 'social_group',
    '#title' => t('Newsletter'),
  );

  $form['mailchimp_api_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Mailchimp API Key'),
    '#required' => TRUE,
    '#default_value' => variable_get('mailchimp_api_key', ''),
    '#description' => t('The API key for your MailChimp account. Get or generate a valid API key at your !apilink.', array('!apilink' => l(t('MailChimp API Dashboard'), 'http://admin.mailchimp.com/account/api'))),
  );

  return $form;
}
