<?php

/**
 * Implements hook_apps_servers_info()
 *
 * Add the uber_publisher_apps server
 */
function uber_publisher_apps_servers_info() {
  $info =  drupal_parse_info_file(drupal_get_path('module', 'uber_publisher_core') . '/uber_publisher_core.info');
  return array(
    'uber_publisher' => array(
      'title' => 'Uber Publisher',
      'description' => 'Apps for Uber Publisher',
      'manifest' => 'http://app_server.local/app/query/Uber%20Publisher',
      //'profile_version' => isset($info['version']) ? $info['version'] : '7.x-1.0',
      //'server_name' => $_SERVER['SERVER_NAME'],
      //'server_ip' => $_SERVER['SERVER_ADDR'],
      //'profile' => $profile,
    ),
  );
}

/**
 * Implements hook_init()
 * 
 * Add a message if this is the levelten apps page.
 */
function uber_publisher_apps_init() {
  if ($_GET['q'] == 'admin/apps/uber_publisher') {
    apps_include('manifest'); 
    $server = apps_servers('uber_publisher');
    // Create args array for substitutions
    $manifest = apps_manifest($server);
    if (isset($manifest['message']) && $manifest['message'] != '') {
      foreach($server as $key => $value) {
        $args['!' . $key] = $value;
      }
      drupal_set_message(format_string($manifest['message'], $args));
    }
  }
}
